# Generated by Django 2.2.5 on 2019-09-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('ano_publicacao', models.DateField(verbose_name='Ano de publicação')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Autor')),
            ],
        ),
    ]
